# Generated by Django 3.1.4 on 2020-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='product',
            name='print_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
